// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class AlertIntervals
{
    public int Id { get; set; }

    public string LineId { get; set; }

    public int? Level { get; set; }

    public TimeSpan? Dt { get; set; }

    public string Description { get; set; }

    public string DescriptionEn { get; set; }

    public string Text { get; set; }

    public virtual ICollection<AlertLevelUsers> AlertLevelUsers { get; set; } = new List<AlertLevelUsers>();
}