// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class AlertLevelUsers
{
    public int Id { get; set; }

    public int? AlertIntervalsId { get; set; }

    public int? UserId { get; set; }

    public virtual AlertIntervals AlertIntervals { get; set; }

    public virtual AlertUsers User { get; set; }
}