// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class AlertUsers
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public int? DescriptionId { get; set; }

    public bool? Active { get; set; }

    public virtual ICollection<AlertLevelUsers> AlertLevelUsers { get; set; } = new List<AlertLevelUsers>();

    public virtual AlertUserDescription Description { get; set; }

    public virtual ICollection<ReportUsers> ReportUsers { get; set; } = new List<ReportUsers>();
}