// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class AlertStations
{
    public int Id { get; set; }

    public string LineId { get; set; }

    public int? StationId { get; set; }

    public string Station { get; set; }

    public string Description { get; set; }

    public bool? Manual { get; set; }

    public string DescriptionEn { get; set; }

    public string Text { get; set; }
}