// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class DownTimeTable
{
    public string LineId { get; set; }

    public DateTime TimeStamp { get; set; }

    public int? Downtime { get; set; }

    public string TypeId { get; set; }

    public DateTime? StartTime { get; set; }

    public int? Muszak { get; set; }

    public int Id { get; set; }

    public string Status { get; set; }

    public DateTime? EndTime { get; set; }

    public string AlertLevel { get; set; }

    public string LastAlertLevel { get; set; }

    public bool? Sent2Cloud { get; set; }

    public TimeSpan? Dt { get; set; }

    public virtual Dttypes Dttypes { get; set; }
}