// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class Dtreport
{
    public int Id { get; set; }

    public DateTime? TimeStamp { get; set; }

    public string UserCode { get; set; }

    public string UserName { get; set; }

    public DateTime StartTime { get; set; }

    public int Shift { get; set; }

    public string LineId { get; set; }

    public int? TypeNumbers { get; set; }

    public int? RequestfromSql { get; set; }

    public int? CurrentfromSql { get; set; }

    public int? GoodfromSql { get; set; }

    public int? EolfromSql { get; set; }

    public int? DownTimefromSql { get; set; }

    public int? Wtnr { get; set; }

    public string Message { get; set; }

    public int? TypeNumberA { get; set; }

    public DateTime? ChangeTimeA { get; set; }

    public string TypeNameA { get; set; }

    public int? RequestfromSqla { get; set; }

    public int? CurrentfromSqla { get; set; }

    public int? CurrentKorrA { get; set; }

    public string CurrentMessageA { get; set; }

    public int? GoodfromSqla { get; set; }

    public int? EolfromSqla { get; set; }

    public int? EolkorrA { get; set; }

    public int? DownTimefromSqla { get; set; }

    public int? WtnrA { get; set; }

    public string MessageA { get; set; }

    public int? TypeNumberB { get; set; }

    public DateTime? ChangeTimeB { get; set; }

    public string TypeNameB { get; set; }

    public int? RequestfromSqlb { get; set; }

    public int? CurrentfromSqlb { get; set; }

    public int? CurrentKorrB { get; set; }

    public string CurrentMessageB { get; set; }

    public int? GoodfromSqlb { get; set; }

    public int? EolfromSqlb { get; set; }

    public int? EolkorrB { get; set; }

    public int? DownTimefromSqlb { get; set; }

    public int? WtnrB { get; set; }

    public string MessageB { get; set; }

    public int? TypeNumberC { get; set; }

    public DateTime? ChangeTimeC { get; set; }

    public string TypeNameC { get; set; }

    public int? RequestfromSqlc { get; set; }

    public int? CurrentfromSqlc { get; set; }

    public int? CurrentKorrC { get; set; }

    public string CurrentMessageC { get; set; }

    public int? GoodfromSqlc { get; set; }

    public int? EolfromSqlc { get; set; }

    public int? EolkorrC { get; set; }

    public int? DownTimefromSqlc { get; set; }

    public int? WtnrC { get; set; }

    public string MessageC { get; set; }

    public int? TypeNumberD { get; set; }

    public DateTime? ChangeTimeD { get; set; }

    public string TypeNameD { get; set; }

    public int? RequestfromSqld { get; set; }

    public int? CurrentfromSqld { get; set; }

    public int? CurrentKorrD { get; set; }

    public string CurrentMessageD { get; set; }

    public int? GoodfromSqld { get; set; }

    public int? EolfromSqld { get; set; }

    public int? EolkorrD { get; set; }

    public int? DownTimefromSqld { get; set; }

    public int? WtnrD { get; set; }

    public string MessageD { get; set; }

    public int? TypeNumberE { get; set; }

    public DateTime? ChangeTimeE { get; set; }

    public string TypeNameE { get; set; }

    public int? RequestfromSqle { get; set; }

    public int? CurrentfromSqle { get; set; }

    public int? CurrentKorrE { get; set; }

    public string CurrentMessageE { get; set; }

    public int? GoodfromSqle { get; set; }

    public int? EolfromSqle { get; set; }

    public int? EolkorrE { get; set; }

    public int? DownTimefromSqle { get; set; }

    public int? WtnrE { get; set; }

    public string MessageE { get; set; }

    public bool SentEmail { get; set; }

    public string Date { get; set; }

    public string Time { get; set; }

    public int? ErrorIda1 { get; set; }

    public int? ErrorIda2 { get; set; }

    public int? ErrorIda3 { get; set; }

    public int? ErrorIda4 { get; set; }

    public int? ErrorIda5 { get; set; }

    public int? ErrorIda6 { get; set; }

    public int? ErrorIda7 { get; set; }

    public int? ErrorIda8 { get; set; }

    public int? ErrorIda9 { get; set; }

    public int? ErrorIda10 { get; set; }

    public int? ErrorIda11 { get; set; }

    public int? ErrorIda12 { get; set; }

    public int? ErrorIda13 { get; set; }

    public int? ErrorIda14 { get; set; }

    public int? ErrorIda15 { get; set; }

    public int? ErrorNra1 { get; set; }

    public int? ErrorNra2 { get; set; }

    public int? ErrorNra3 { get; set; }

    public int? ErrorNra4 { get; set; }

    public int? ErrorNra5 { get; set; }

    public int? ErrorNra6 { get; set; }

    public int? ErrorNra7 { get; set; }

    public int? ErrorNra8 { get; set; }

    public int? ErrorNra9 { get; set; }

    public int? ErrorNra10 { get; set; }

    public int? ErrorNra11 { get; set; }

    public int? ErrorNra12 { get; set; }

    public int? ErrorNra13 { get; set; }

    public int? ErrorNra14 { get; set; }

    public int? ErrorNra15 { get; set; }

    public int? ErrorIdb1 { get; set; }

    public int? ErrorIdb2 { get; set; }

    public int? ErrorIdb3 { get; set; }

    public int? ErrorIdb4 { get; set; }

    public int? ErrorIdb5 { get; set; }

    public int? ErrorIdb6 { get; set; }

    public int? ErrorIdb7 { get; set; }

    public int? ErrorIdb8 { get; set; }

    public int? ErrorIdb9 { get; set; }

    public int? ErrorIdb10 { get; set; }

    public int? ErrorIdb11 { get; set; }

    public int? ErrorIdb12 { get; set; }

    public int? ErrorIdb13 { get; set; }

    public int? ErrorIdb14 { get; set; }

    public int? ErrorIdb15 { get; set; }

    public int? ErrorNrb1 { get; set; }

    public int? ErrorNrb2 { get; set; }

    public int? ErrorNrb3 { get; set; }

    public int? ErrorNrb4 { get; set; }

    public int? ErrorNrb5 { get; set; }

    public int? ErrorNrb6 { get; set; }

    public int? ErrorNrb7 { get; set; }

    public int? ErrorNrb8 { get; set; }

    public int? ErrorNrb9 { get; set; }

    public int? ErrorNrb10 { get; set; }

    public int? ErrorNrb11 { get; set; }

    public int? ErrorNrb12 { get; set; }

    public int? ErrorNrb13 { get; set; }

    public int? ErrorNrb14 { get; set; }

    public int? ErrorNrb15 { get; set; }

    public int? ErrorIdc1 { get; set; }

    public int? ErrorIdc2 { get; set; }

    public int? ErrorIdc3 { get; set; }

    public int? ErrorIdc4 { get; set; }

    public int? ErrorIdc5 { get; set; }

    public int? ErrorIdc6 { get; set; }

    public int? ErrorIdc7 { get; set; }

    public int? ErrorIdc8 { get; set; }

    public int? ErrorIdc9 { get; set; }

    public int? ErrorIdc10 { get; set; }

    public int? ErrorIdc11 { get; set; }

    public int? ErrorIdc12 { get; set; }

    public int? ErrorIdc13 { get; set; }

    public int? ErrorIdc14 { get; set; }

    public int? ErrorIdc15 { get; set; }

    public int? ErrorNrc1 { get; set; }

    public int? ErrorNrc2 { get; set; }

    public int? ErrorNrc3 { get; set; }

    public int? ErrorNrc4 { get; set; }

    public int? ErrorNrc5 { get; set; }

    public int? ErrorNrc6 { get; set; }

    public int? ErrorNrc7 { get; set; }

    public int? ErrorNrc8 { get; set; }

    public int? ErrorNrc9 { get; set; }

    public int? ErrorNrc10 { get; set; }

    public int? ErrorNrc11 { get; set; }

    public int? ErrorNrc12 { get; set; }

    public int? ErrorNrc13 { get; set; }

    public int? ErrorNrc14 { get; set; }

    public int? ErrorNrc15 { get; set; }

    public int? ErrorIdd1 { get; set; }

    public int? ErrorIdd2 { get; set; }

    public int? ErrorIdd3 { get; set; }

    public int? ErrorIdd4 { get; set; }

    public int? ErrorIdd5 { get; set; }

    public int? ErrorIdd6 { get; set; }

    public int? ErrorIdd7 { get; set; }

    public int? ErrorIdd8 { get; set; }

    public int? ErrorIdd9 { get; set; }

    public int? ErrorIdd10 { get; set; }

    public int? ErrorIdd11 { get; set; }

    public int? ErrorIdd12 { get; set; }

    public int? ErrorIdd13 { get; set; }

    public int? ErrorIdd14 { get; set; }

    public int? ErrorIdd15 { get; set; }

    public int? ErrorNrd1 { get; set; }

    public int? ErrorNrd2 { get; set; }

    public int? ErrorNrd3 { get; set; }

    public int? ErrorNrd4 { get; set; }

    public int? ErrorNrd5 { get; set; }

    public int? ErrorNrd6 { get; set; }

    public int? ErrorNrd7 { get; set; }

    public int? ErrorNrd8 { get; set; }

    public int? ErrorNrd9 { get; set; }

    public int? ErrorNrd10 { get; set; }

    public int? ErrorNrd11 { get; set; }

    public int? ErrorNrd12 { get; set; }

    public int? ErrorNrd13 { get; set; }

    public int? ErrorNrd14 { get; set; }

    public int? ErrorNrd15 { get; set; }

    public int? ErrorIde1 { get; set; }

    public int? ErrorIde2 { get; set; }

    public int? ErrorIde3 { get; set; }

    public int? ErrorIde4 { get; set; }

    public int? ErrorIde5 { get; set; }

    public int? ErrorIde6 { get; set; }

    public int? ErrorIde7 { get; set; }

    public int? ErrorIde8 { get; set; }

    public int? ErrorIde9 { get; set; }

    public int? ErrorIde10 { get; set; }

    public int? ErrorIde11 { get; set; }

    public int? ErrorIde12 { get; set; }

    public int? ErrorIde13 { get; set; }

    public int? ErrorIde14 { get; set; }

    public int? ErrorIde15 { get; set; }

    public int? ErrorNre1 { get; set; }

    public int? ErrorNre2 { get; set; }

    public int? ErrorNre3 { get; set; }

    public int? ErrorNre4 { get; set; }

    public int? ErrorNre5 { get; set; }

    public int? ErrorNre6 { get; set; }

    public int? ErrorNre7 { get; set; }

    public int? ErrorNre8 { get; set; }

    public int? ErrorNre9 { get; set; }

    public int? ErrorNre10 { get; set; }

    public int? ErrorNre11 { get; set; }

    public int? ErrorNre12 { get; set; }

    public int? ErrorNre13 { get; set; }

    public int? ErrorNre14 { get; set; }

    public int? ErrorNre15 { get; set; }

    public virtual IfsFailureCodeTable ErrorIda10Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIda11Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIda12Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIda13Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIda14Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIda15Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIda1Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIda2Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIda3Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIda4Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIda5Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIda6Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIda7Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIda8Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIda9Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdb10Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdb11Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdb12Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdb13Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdb14Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdb15Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdb1Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdb2Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdb3Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdb4Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdb5Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdb6Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdb7Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdb8Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdb9Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdc10Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdc11Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdc12Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdc13Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdc14Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdc15Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdc1Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdc2Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdc3Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdc4Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdc5Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdc6Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdc7Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdc8Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdc9Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdd10Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdd11Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdd12Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdd13Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdd14Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdd15Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdd1Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdd2Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdd3Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdd4Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdd5Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdd6Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdd7Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdd8Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIdd9Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIde10Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIde11Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIde12Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIde13Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIde14Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIde15Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIde1Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIde2Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIde3Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIde4Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIde5Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIde6Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIde7Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIde8Navigation { get; set; }

    public virtual IfsFailureCodeTable ErrorIde9Navigation { get; set; }
}