// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class DttypesGroup
{
    public int? DtgroupId { get; set; }

    public string LineId { get; set; }

    public string Description { get; set; }

    public string DescriptionEn { get; set; }

    public int Id { get; set; }

    public virtual ICollection<Dttypes> Dttypes { get; set; } = new List<Dttypes>();
}