// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class Dttypes
{
    public string LineId { get; set; }

    public string CodeId { get; set; }

    public string Description { get; set; }

    public string DescriptionEn { get; set; }

    public int Id { get; set; }

    public int? DtgroupId { get; set; }

    public string Search { get; set; }

    public string SearchEn { get; set; }

    public bool? OeedownTime { get; set; }

    public virtual ICollection<Cttable> Cttable { get; set; } = new List<Cttable>();

    public virtual ICollection<DownTimeTable> DownTimeTable { get; set; } = new List<DownTimeTable>();

    public virtual DttypesGroup DttypesGroup { get; set; }
}