// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class EasyMesstatus
{
    public int Id { get; set; }

    public string Status { get; set; }

    public int SystemParamId { get; set; }

    public virtual ICollection<EasyMesjob> EasyMesjob { get; set; } = new List<EasyMesjob>();

    public virtual SystemParamTable SystemParam { get; set; }
}