// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EIS.EISModels;

public partial class EasyMesjob
{
    public int Id { get; set; }

    public int TtstypesId { get; set; }

    public int PlanQty { get; set; }

    public int ProducedQty { get; set; }

    public int? Eol { get; set; }

    public int? BadParts { get; set; }

    public DateTime CalcStart { get; set; }

    public DateTime? CalcEnd { get; set; }

    public DateTime? JobStart { get; set; }

    public DateTime? JobTimeStamp { get; set; }

    public DateTime? JobFinish { get; set; }

    public int SystemParamId { get; set; }

    public bool Started { get; set; }

    public bool Closed { get; set; }

    public bool Running { get; set; }

    public bool Stopped { get; set; }

    public int? StatusId { get; set; }

    public DateTime? TargetEnd { get; set; }

    public double Percentage { get; set; }

    public bool CalcAuto { get; set; }

    public bool CalcTargetEnd { get; set; }

    public int RowNo { get; set; }

    public DateTime? TargetStart { get; set; }

    public bool CalcTargetStart { get; set; }

    public virtual EasyMesstatus Status { get; set; }

    public virtual SystemParamTable SystemParam { get; set; }

    public virtual EasyMesttstypes Ttstypes { get; set; }
}