// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIS.EISModels
{
    public partial class GetLZKefetartoIdResult
    {
        public int KefetartoId { get; set; }
        public string Kefetartoszam { get; set; }
        public string SearchType { get; set; }
    }
}
