// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIS.EISModels
{
    public partial class GetLZCategoryListResult
    {
        public int Azonosító { get; set; }
        public string Neve { get; set; }
        public string Cég { get; set; }
        public string Kategória { get; set; }
        public double? Órák { get; set; }
    }
}
