// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIS.EISModels
{
    public partial class GetLZDolgozoResult
    {
        public int Id { get; set; }
        public int DolgozoID { get; set; }
        public string DolgozoNeve { get; set; }
        public int Irsz { get; set; }
        public string Varos { get; set; }
        public string Utca_hrsz { get; set; }
        public string Telefonszam { get; set; }
        public string Megjegyzes { get; set; }
        public bool Active { get; set; }
        public DateTime BeDat { get; set; }
        public DateTime? KiDat { get; set; }
        public DateTime SzDat { get; set; }
        public int Munkaido { get; set; }
        public string Search { get; set; }
    }
}
