// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EIS.EISModels;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace EIS.EISModels
{
    public partial interface IEISDBContextProcedures
    {
        Task<int> GetLZCategoryAsync(string Year, string Month, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> GetLZCategoryEnAsync(string Year, string Month, string Shift, string Code, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> GetLZHoursAsync(string Year, string Month, string Shift, string Code, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> GetLZHoursENAsync(string Year, string Month, string Shift, string Code, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> GetLZSzabadsagAsync(string Year, string Month, string Shift, string Code, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> GetLZSzabadsagENAsync(string Year, string Month, string Shift, string Code, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ReadDTSPivotResult>> ReadDTSPivotAsync(string LineID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
