// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class IfsFailureCodeTable
{
    public int Id { get; set; }

    public string LineId { get; set; }

    public string FailureId { get; set; }

    public string Description { get; set; }

    public string DescriptionEn { get; set; }

    public int FailureClassId { get; set; }

    public int DetectionId { get; set; }

    public string Search { get; set; }

    public string SearchEn { get; set; }

    public virtual IfsDetectionTable Detection { get; set; }

    public virtual ICollection<Dtreport> DtreportErrorIda10Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIda11Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIda12Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIda13Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIda14Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIda15Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIda1Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIda2Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIda3Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIda4Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIda5Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIda6Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIda7Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIda8Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIda9Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdb10Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdb11Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdb12Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdb13Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdb14Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdb15Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdb1Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdb2Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdb3Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdb4Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdb5Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdb6Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdb7Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdb8Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdb9Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdc10Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdc11Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdc12Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdc13Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdc14Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdc15Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdc1Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdc2Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdc3Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdc4Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdc5Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdc6Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdc7Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdc8Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdc9Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdd10Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdd11Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdd12Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdd13Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdd14Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdd15Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdd1Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdd2Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdd3Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdd4Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdd5Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdd6Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdd7Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdd8Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIdd9Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIde10Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIde11Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIde12Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIde13Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIde14Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIde15Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIde1Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIde2Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIde3Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIde4Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIde5Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIde6Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIde7Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIde8Navigation { get; set; } = new List<Dtreport>();

    public virtual ICollection<Dtreport> DtreportErrorIde9Navigation { get; set; } = new List<Dtreport>();

    public virtual IfsFailureClassCodeTable FailureClass { get; set; }

    public virtual ICollection<IfsValueTable> IfsValueTable { get; set; } = new List<IfsValueTable>();
}