// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class IfsHeaderTable
{
    public int Id { get; set; }

    public string LineId { get; set; }

    public DateTime StartTime { get; set; }

    public int ShiftId { get; set; }

    public int? AllParts { get; set; }

    public int? BadParts { get; set; }

    public int? GoodParts { get; set; }

    public double? FailureRate { get; set; }

    public int? SettingsParts { get; set; }

    public int? DroppedParts { get; set; }

    public double? WorkingHours { get; set; }

    public virtual IfsValueTable IfsValueTable { get; set; }

    public virtual ShiftsTable ShiftsTable { get; set; }
}