// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class Kpiunit
{
    public int Id { get; set; }

    public string NameEn { get; set; }

    public string NameHu { get; set; }

    public string NameDe { get; set; }

    public string Format { get; set; }

    public virtual ICollection<Kpiheader> Kpiheader { get; set; } = new List<Kpiheader>();
}