// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class Kpivalues
{
    public int Id { get; set; }

    public int Year { get; set; }

    public int KpiheaderId { get; set; }

    public double? TargetPrev { get; set; }

    public double? Target01 { get; set; }

    public double? Target02 { get; set; }

    public double? Target03 { get; set; }

    public double? Target04 { get; set; }

    public double? Target05 { get; set; }

    public double? Target06 { get; set; }

    public double? Target07 { get; set; }

    public double? Target08 { get; set; }

    public double? Target09 { get; set; }

    public double? Target10 { get; set; }

    public double? Target11 { get; set; }

    public double? Target12 { get; set; }

    public double? TargetNext { get; set; }

    public double? ValuePrev { get; set; }

    public double? Value01 { get; set; }

    public double? Value02 { get; set; }

    public double? Value03 { get; set; }

    public double? Value04 { get; set; }

    public double? Value05 { get; set; }

    public double? Value06 { get; set; }

    public double? Value07 { get; set; }

    public double? Value08 { get; set; }

    public double? Value09 { get; set; }

    public double? Value10 { get; set; }

    public double? Value11 { get; set; }

    public double? Value12 { get; set; }

    public double? ValueNext { get; set; }

    public int? SortedId { get; set; }

    public bool? Visible { get; set; }

    public virtual Kpiheader Kpiheader { get; set; }
}