// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class LzIntervalTable
{
    public int Id { get; set; }

    public int DolgozoId { get; set; }

    public DateTime DatumTol { get; set; }

    public DateTime DatumIg { get; set; }

    public string Megjegyzes { get; set; }

    public double Ora { get; set; }

    public int MuveletId { get; set; }
}