// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class LzKefetartotipuslistaTable
{
    public int Id { get; set; }

    public string Tipus { get; set; }
}