// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class LzMuveletReszletTable
{
    public int Id { get; set; }

    public int Muveletszam { get; set; }

    public string Muveletreszlet { get; set; }

    public string Description { get; set; }

    public bool Interval { get; set; }

    public bool Munkanap { get; set; }

    public bool Unnep { get; set; }

    public bool Pihenonap { get; set; }

    public bool AllCode { get; set; }

    public bool Empty { get; set; }

    public string Search { get; set; }
}