// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class LzMunkanapTable
{
    public int Id { get; set; }

    public DateTime Datum { get; set; }

    public int MunkaId { get; set; }

    public string Hetnapja { get; set; }
}