// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class Mesevents
{
    public int Id { get; set; }

    public string LineId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime EventStart { get; set; }

    public DateTime? EventEnd { get; set; }

    public bool AllDay { get; set; }

    public string TextColor { get; set; }

    public string BackgroundColor { get; set; }

    public string BorderColor { get; set; }

    public string DisplayOrder { get; set; }
}