// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class MesproductPlan
{
    public int Id { get; set; }

    public string LineId { get; set; }

    public DateTime StartTime { get; set; }

    public int Muszak { get; set; }

    public bool Active { get; set; }

    public bool Maintenance { get; set; }

    public int WorkerId1 { get; set; }

    public int WorkerId2 { get; set; }

    public TimeSpan? Maintenancefrom { get; set; }

    public TimeSpan? Maintenanceto { get; set; }

    public virtual Mesworker WorkerId1Navigation { get; set; }

    public virtual Mesworker WorkerId2Navigation { get; set; }
}