// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class MesproductPlanWeek
{
    public int Id { get; set; }

    public string LineId { get; set; }

    public int Year { get; set; }

    public int Week { get; set; }

    public bool Active01 { get; set; }

    public bool Maintenance01 { get; set; }

    public int Mtype01 { get; set; }

    public TimeSpan? From01 { get; set; }

    public TimeSpan? To01 { get; set; }

    public int WorkerId011 { get; set; }

    public int WorkerId012 { get; set; }

    public bool Active02 { get; set; }

    public bool Maintenance02 { get; set; }

    public int Mtype02 { get; set; }

    public TimeSpan? From02 { get; set; }

    public TimeSpan? To02 { get; set; }

    public int WorkerId021 { get; set; }

    public int WorkerId022 { get; set; }

    public bool Active03 { get; set; }

    public bool Maintenance03 { get; set; }

    public int Mtype03 { get; set; }

    public TimeSpan? From03 { get; set; }

    public TimeSpan? To03 { get; set; }

    public int WorkerId031 { get; set; }

    public int WorkerId032 { get; set; }

    public bool Active11 { get; set; }

    public bool Maintenance11 { get; set; }

    public int Mtype11 { get; set; }

    public TimeSpan? From11 { get; set; }

    public TimeSpan? To11 { get; set; }

    public int WorkerId111 { get; set; }

    public int WorkerId112 { get; set; }

    public bool Active12 { get; set; }

    public bool Maintenance12 { get; set; }

    public int Mtype12 { get; set; }

    public TimeSpan? From12 { get; set; }

    public TimeSpan? To12 { get; set; }

    public int WorkerId121 { get; set; }

    public int WorkerId122 { get; set; }

    public bool Active13 { get; set; }

    public bool Maintenance13 { get; set; }

    public int Mtype13 { get; set; }

    public TimeSpan? From13 { get; set; }

    public TimeSpan? To13 { get; set; }

    public int WorkerId131 { get; set; }

    public int WorkerId132 { get; set; }

    public bool Active21 { get; set; }

    public bool Maintenance21 { get; set; }

    public int Mtype21 { get; set; }

    public TimeSpan? From21 { get; set; }

    public TimeSpan? To21 { get; set; }

    public int WorkerId211 { get; set; }

    public int WorkerId212 { get; set; }

    public bool Active22 { get; set; }

    public bool Maintenance22 { get; set; }

    public int Mtype22 { get; set; }

    public TimeSpan? From22 { get; set; }

    public TimeSpan? To22 { get; set; }

    public int WorkerId221 { get; set; }

    public int WorkerId222 { get; set; }

    public bool Active23 { get; set; }

    public bool Maintenance23 { get; set; }

    public int Mtype23 { get; set; }

    public TimeSpan? From23 { get; set; }

    public TimeSpan? To23 { get; set; }

    public int WorkerId231 { get; set; }

    public int WorkerId232 { get; set; }

    public bool Active31 { get; set; }

    public bool Maintenance31 { get; set; }

    public int Mtype31 { get; set; }

    public TimeSpan? From31 { get; set; }

    public TimeSpan? To31 { get; set; }

    public int WorkerId311 { get; set; }

    public int WorkerId312 { get; set; }

    public bool Active32 { get; set; }

    public bool Maintenance32 { get; set; }

    public int Mtype32 { get; set; }

    public TimeSpan? From32 { get; set; }

    public TimeSpan? To32 { get; set; }

    public int WorkerId321 { get; set; }

    public int WorkerId322 { get; set; }

    public bool Active33 { get; set; }

    public bool Maintenance33 { get; set; }

    public int Mtype33 { get; set; }

    public TimeSpan? From33 { get; set; }

    public TimeSpan? To33 { get; set; }

    public int WorkerId331 { get; set; }

    public int WorkerId332 { get; set; }

    public bool Active41 { get; set; }

    public bool Maintenance41 { get; set; }

    public int Mtype41 { get; set; }

    public TimeSpan? From41 { get; set; }

    public TimeSpan? To41 { get; set; }

    public int WorkerId411 { get; set; }

    public int WorkerId412 { get; set; }

    public bool Active42 { get; set; }

    public bool Maintenance42 { get; set; }

    public int Mtype42 { get; set; }

    public TimeSpan? From42 { get; set; }

    public TimeSpan? To42 { get; set; }

    public int WorkerId421 { get; set; }

    public int WorkerId422 { get; set; }

    public bool Active43 { get; set; }

    public bool Maintenance43 { get; set; }

    public int Mtype43 { get; set; }

    public TimeSpan? From43 { get; set; }

    public TimeSpan? To43 { get; set; }

    public int WorkerId431 { get; set; }

    public int WorkerId432 { get; set; }

    public bool Active51 { get; set; }

    public bool Maintenance51 { get; set; }

    public int Mtype51 { get; set; }

    public TimeSpan? From51 { get; set; }

    public TimeSpan? To51 { get; set; }

    public int WorkerId511 { get; set; }

    public int WorkerId512 { get; set; }

    public bool Active52 { get; set; }

    public bool Maintenance52 { get; set; }

    public int Mtype52 { get; set; }

    public TimeSpan? From52 { get; set; }

    public TimeSpan? To52 { get; set; }

    public int WorkerId521 { get; set; }

    public int WorkerId522 { get; set; }

    public bool Active53 { get; set; }

    public bool Maintenance53 { get; set; }

    public int Mtype53 { get; set; }

    public TimeSpan? From53 { get; set; }

    public TimeSpan? To53 { get; set; }

    public int WorkerId531 { get; set; }

    public int WorkerId532 { get; set; }

    public bool Active61 { get; set; }

    public bool Maintenance61 { get; set; }

    public int Mtype61 { get; set; }

    public TimeSpan? From61 { get; set; }

    public TimeSpan? To61 { get; set; }

    public int WorkerId611 { get; set; }

    public int WorkerId612 { get; set; }

    public bool Active62 { get; set; }

    public bool Maintenance62 { get; set; }

    public int Mtype62 { get; set; }

    public TimeSpan? From62 { get; set; }

    public TimeSpan? To62 { get; set; }

    public int WorkerId621 { get; set; }

    public int WorkerId622 { get; set; }

    public bool Active63 { get; set; }

    public bool Maintenance63 { get; set; }

    public int Mtype63 { get; set; }

    public TimeSpan? From63 { get; set; }

    public TimeSpan? To63 { get; set; }

    public int WorkerId631 { get; set; }

    public int WorkerId632 { get; set; }

    public DateTime StartTime { get; set; }

    public bool? Newflag { get; set; }
}