// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class MesproductPlanWeekTemp
{
    public int Id { get; set; }

    public string LineId { get; set; }

    public int Year { get; set; }

    public int Week { get; set; }

    public bool Active01 { get; set; }

    public bool Active11 { get; set; }

    public bool Active21 { get; set; }

    public bool Active31 { get; set; }

    public bool Active41 { get; set; }

    public bool Active51 { get; set; }

    public bool Active61 { get; set; }

    public int WorkerId11 { get; set; }

    public int WorkerId12 { get; set; }

    public bool Active02 { get; set; }

    public bool Active12 { get; set; }

    public bool Active22 { get; set; }

    public bool Active32 { get; set; }

    public bool Active42 { get; set; }

    public bool Active52 { get; set; }

    public bool Active62 { get; set; }

    public int WorkerId21 { get; set; }

    public int WorkerId22 { get; set; }

    public bool Active03 { get; set; }

    public bool Active13 { get; set; }

    public bool Active23 { get; set; }

    public bool Active33 { get; set; }

    public bool Active43 { get; set; }

    public bool Active53 { get; set; }

    public bool Active63 { get; set; }

    public int WorkerId31 { get; set; }

    public int WorkerId32 { get; set; }

    public DateTime StartTime { get; set; }

    public bool? Newflag { get; set; }
}