// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class Mesworker
{
    public int Id { get; set; }

    public string LineId { get; set; }

    public string WorkerName { get; set; }

    public virtual ICollection<MesproductPlan> MesproductPlanWorkerId1Navigation { get; set; } = new List<MesproductPlan>();

    public virtual ICollection<MesproductPlan> MesproductPlanWorkerId2Navigation { get; set; } = new List<MesproductPlan>();
}