// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIS.EISModels
{
    public partial class ReadDTSPivotResult
    {
        public string LineID { get; set; }
        public DateTime? Starttime { get; set; }
        public int? Shift { get; set; }
        public DateTime TimeStamp { get; set; }
        public int WTNR { get; set; }
        public int? Type { get; set; }
        public DateTime? St01 { get; set; }
        public DateTime? St02 { get; set; }
        public DateTime? St03 { get; set; }
        public DateTime? St04 { get; set; }
        public DateTime? St05 { get; set; }
        public DateTime? St5B { get; set; }
        public DateTime? St06 { get; set; }
        public DateTime? St07 { get; set; }
        public DateTime? St08 { get; set; }
        public DateTime? St09 { get; set; }
        public DateTime? St10 { get; set; }
        public DateTime? St12 { get; set; }
        public DateTime? St13 { get; set; }
        public DateTime? St14 { get; set; }
        public DateTime? St15 { get; set; }
        public DateTime? St17 { get; set; }
        public DateTime? St18 { get; set; }
        public DateTime? St19 { get; set; }
        public DateTime? St20 { get; set; }
        public DateTime? St21 { get; set; }
        public DateTime? dt2 { get; set; }
        public DateTime? dt3 { get; set; }
        public DateTime? dt4 { get; set; }
        public DateTime? dt5 { get; set; }
        public DateTime? dt5b { get; set; }
        public DateTime? dt6 { get; set; }
        public DateTime? dt7 { get; set; }
        public DateTime? dt8 { get; set; }
        public DateTime? dt9 { get; set; }
        public DateTime? dt10 { get; set; }
        public DateTime? dt12 { get; set; }
        public DateTime? dt13 { get; set; }
        public DateTime? dt14 { get; set; }
        public DateTime? dt15 { get; set; }
        public DateTime? dt17 { get; set; }
        public DateTime? dt18 { get; set; }
        public DateTime? dt19 { get; set; }
        public DateTime? dt20 { get; set; }
        public DateTime? dt21 { get; set; }
    }
}
