// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class ReportUsers
{
    public int Id { get; set; }

    public int SystemParamId { get; set; }

    public int UserId { get; set; }

    public virtual SystemParamTable SystemParam { get; set; }

    public virtual AlertUsers User { get; set; }
}