// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class ShiftsTable
{
    public string LineId { get; set; }

    public DateTime Starttime { get; set; }

    public int Muszak { get; set; }

    public string Start { get; set; }

    public string Stop { get; set; }

    public int? Elvart { get; set; }

    public int? Gyartott { get; set; }

    public float? Szazalek { get; set; }

    public int? Allasido { get; set; }

    public string StartH00 { get; set; }

    public string StopH00 { get; set; }

    public int? ElvartH00 { get; set; }

    public int? GyartottH00 { get; set; }

    public int? AllasidoH00 { get; set; }

    public float? SzazalekH00 { get; set; }

    public int? Okok0H00 { get; set; }

    public int? Okok1H00 { get; set; }

    public int? Okok2H00 { get; set; }

    public int? Okok3H00 { get; set; }

    public int? Okok4H00 { get; set; }

    public int? Okok5H00 { get; set; }

    public string StartH01 { get; set; }

    public string StopH01 { get; set; }

    public int? ElvartH01 { get; set; }

    public int? GyartottH01 { get; set; }

    public float? SzazalekH01 { get; set; }

    public int? AllasidoH01 { get; set; }

    public int? Okok0H01 { get; set; }

    public int? Okok1H01 { get; set; }

    public int? Okok2H01 { get; set; }

    public int? Okok3H01 { get; set; }

    public int? Okok4H01 { get; set; }

    public int? Okok5H01 { get; set; }

    public string StartH02 { get; set; }

    public string StopH02 { get; set; }

    public int? ElvartH02 { get; set; }

    public int? GyartottH02 { get; set; }

    public float? SzazalekH02 { get; set; }

    public int? AllasidoH02 { get; set; }

    public int? Okok0H02 { get; set; }

    public int? Okok1H02 { get; set; }

    public int? Okok2H02 { get; set; }

    public int? Okok3H02 { get; set; }

    public int? Okok4H02 { get; set; }

    public int? Okok5H02 { get; set; }

    public string StartH03 { get; set; }

    public string StopH03 { get; set; }

    public int? ElvartH03 { get; set; }

    public int? GyartottH03 { get; set; }

    public float? SzazalekH03 { get; set; }

    public int? AllasidoH03 { get; set; }

    public int? Okok0H03 { get; set; }

    public int? Okok1H03 { get; set; }

    public int? Okok2H03 { get; set; }

    public int? Okok3H03 { get; set; }

    public int? Okok4H03 { get; set; }

    public int? Okok5H03 { get; set; }

    public string StartH04 { get; set; }

    public string StopH04 { get; set; }

    public int? ElvartH04 { get; set; }

    public int? GyartottH04 { get; set; }

    public float? SzazalekH04 { get; set; }

    public int? AllasidoH04 { get; set; }

    public int? Okok0H04 { get; set; }

    public int? Okok1H04 { get; set; }

    public int? Okok2H04 { get; set; }

    public int? Okok3H04 { get; set; }

    public int? Okok4H04 { get; set; }

    public int? Okok5H04 { get; set; }

    public string StartH05 { get; set; }

    public string StopH05 { get; set; }

    public int? ElvartH05 { get; set; }

    public int? GyartottH05 { get; set; }

    public float? SzazalekH05 { get; set; }

    public int? AllasidoH05 { get; set; }

    public int? Okok0H05 { get; set; }

    public int? Okok1H05 { get; set; }

    public int? Okok2H05 { get; set; }

    public int? Okok3H05 { get; set; }

    public int? Okok4H05 { get; set; }

    public int? Okok5H05 { get; set; }

    public string StartH06 { get; set; }

    public string StopH06 { get; set; }

    public int? ElvartH06 { get; set; }

    public int? GyartottH06 { get; set; }

    public float? SzazalekH06 { get; set; }

    public float? AllasidoH06 { get; set; }

    public int? Okok0H06 { get; set; }

    public int? Okok1H06 { get; set; }

    public int? Okok2H06 { get; set; }

    public int? Okok3H06 { get; set; }

    public int? Okok4H06 { get; set; }

    public int? Okok5H06 { get; set; }

    public string StartH07 { get; set; }

    public string StopH07 { get; set; }

    public int? ElvartH07 { get; set; }

    public int? GyartottH07 { get; set; }

    public float? SzazalekH07 { get; set; }

    public int? AllasidoH07 { get; set; }

    public int? Okok0H07 { get; set; }

    public int? Okok1H07 { get; set; }

    public int? Okok2H07 { get; set; }

    public int? Okok3H07 { get; set; }

    public int? Okok4H07 { get; set; }

    public int? Okok5H07 { get; set; }

    public string StartH08 { get; set; }

    public string StopH08 { get; set; }

    public int? ElvartH08 { get; set; }

    public int? GyartottH08 { get; set; }

    public float? SzazalekH08 { get; set; }

    public int? AllasidoH08 { get; set; }

    public int? Okok0H08 { get; set; }

    public int? Okok1H08 { get; set; }

    public int? Okok2H08 { get; set; }

    public int? Okok3H08 { get; set; }

    public int? Okok4H08 { get; set; }

    public int? Okok5H08 { get; set; }

    public string StartH09 { get; set; }

    public string StopH09 { get; set; }

    public int? ElvartH09 { get; set; }

    public int? GyartottH09 { get; set; }

    public float? SzazalekH09 { get; set; }

    public int? AllasidoH09 { get; set; }

    public int? Okok0H09 { get; set; }

    public int? Okok1H09 { get; set; }

    public int? Okok2H09 { get; set; }

    public int? Okok3H09 { get; set; }

    public int? Okok4H09 { get; set; }

    public int? Okok5H09 { get; set; }

    public byte[] LastUpdate { get; set; }

    public float? Run { get; set; }

    public float? Run01 { get; set; }

    public float? Run02 { get; set; }

    public float? Run03 { get; set; }

    public float? Run04 { get; set; }

    public float? Run05 { get; set; }

    public float? Run06 { get; set; }

    public float? Run07 { get; set; }

    public float? Run08 { get; set; }

    public float? Run09 { get; set; }

    public float? Slow { get; set; }

    public float? Slow01 { get; set; }

    public float? Slow02 { get; set; }

    public float? Slow03 { get; set; }

    public float? Slow04 { get; set; }

    public float? Slow05 { get; set; }

    public float? Slow06 { get; set; }

    public float? Slow07 { get; set; }

    public float? Slow08 { get; set; }

    public float? Slow09 { get; set; }

    public float? Ms { get; set; }

    public float? Ms01 { get; set; }

    public float? Ms02 { get; set; }

    public float? Ms03 { get; set; }

    public float? Ms04 { get; set; }

    public float? Ms05 { get; set; }

    public float? Ms06 { get; set; }

    public float? Ms07 { get; set; }

    public float? Ms08 { get; set; }

    public float? Ms09 { get; set; }

    public float? DownTime { get; set; }

    public float? DownTime01 { get; set; }

    public float? DownTime02 { get; set; }

    public float? DownTime03 { get; set; }

    public float? DownTime04 { get; set; }

    public float? DownTime05 { get; set; }

    public float? DownTime06 { get; set; }

    public float? DownTime07 { get; set; }

    public float? DownTime08 { get; set; }

    public float? DownTime09 { get; set; }

    public float? Ct { get; set; }

    public float? Cct { get; set; }

    public int? Nio100 { get; set; }

    public int? Nio08 { get; set; }

    public int? Nio22 { get; set; }

    public int? Nio23 { get; set; }

    public int? Io22 { get; set; }

    public int? Io23 { get; set; }

    public int? Io100 { get; set; }

    public int? Rework { get; set; }

    public int? Goodparts { get; set; }

    public int? Opertime { get; set; }

    public int? Breaktime { get; set; }

    public int? Prodtime { get; set; }

    public int? Dtime { get; set; }

    public int? Runtime { get; set; }

    public float? A { get; set; }

    public float? P { get; set; }

    public float? Q { get; set; }

    public float? Oee { get; set; }

    public float? Oeetarget { get; set; }

    public int? Week { get; set; }

    public DateTime? Date { get; set; }

    public int? PGyartott { get; set; }

    public int? PGyartottH00 { get; set; }

    public int? PGyartottH01 { get; set; }

    public int? PGyartottH02 { get; set; }

    public int? PGyartottH03 { get; set; }

    public int? PGyartottH04 { get; set; }

    public int? PGyartottH05 { get; set; }

    public int? PGyartottH06 { get; set; }

    public int? PGyartottH07 { get; set; }

    public int? PGyartottH08 { get; set; }

    public int? PGyartottH09 { get; set; }

    public double? Ciklusido { get; set; }

    public double? CiklusidoH00 { get; set; }

    public double? CiklusidoH01 { get; set; }

    public double? CiklusidoH02 { get; set; }

    public double? CiklusidoH03 { get; set; }

    public double? CiklusidoH04 { get; set; }

    public double? CiklusidoH05 { get; set; }

    public double? CiklusidoH06 { get; set; }

    public double? CiklusidoH07 { get; set; }

    public double? CiklusidoH08 { get; set; }

    public double? CiklusidoH09 { get; set; }

    public double? Cttarget { get; set; }

    public int? Selejt { get; set; }

    public int? SelejtH00 { get; set; }

    public int? SelejtH01 { get; set; }

    public int? SelejtH02 { get; set; }

    public int? SelejtH03 { get; set; }

    public int? SelejtH04 { get; set; }

    public int? SelejtH05 { get; set; }

    public int? SelejtH06 { get; set; }

    public int? SelejtH07 { get; set; }

    public int? SelejtH08 { get; set; }

    public int? SelejtH09 { get; set; }

    public double? SelejtRata { get; set; }

    public double? SelejtRataH00 { get; set; }

    public double? SelejtRataH01 { get; set; }

    public double? SelejtRataH02 { get; set; }

    public double? SelejtRataH03 { get; set; }

    public double? SelejtRataH04 { get; set; }

    public double? SelejtRataH05 { get; set; }

    public double? SelejtRataH06 { get; set; }

    public double? SelejtRataH07 { get; set; }

    public double? SelejtRataH08 { get; set; }

    public double? SelejtRataH09 { get; set; }

    public double? SelejtRataTarget { get; set; }

    public int? Munkaido { get; set; }

    public int? MunkaidoH00 { get; set; }

    public int? MunkaidoH01 { get; set; }

    public int? MunkaidoH02 { get; set; }

    public int? MunkaidoH03 { get; set; }

    public int? MunkaidoH04 { get; set; }

    public int? MunkaidoH05 { get; set; }

    public int? MunkaidoH06 { get; set; }

    public int? MunkaidoH07 { get; set; }

    public int? MunkaidoH08 { get; set; }

    public int? MunkaidoH09 { get; set; }

    public int? Selejt00 { get; set; }

    public int? Selejt10 { get; set; }

    public int? Selejt20 { get; set; }

    public int? Selejt30 { get; set; }

    public int? Selejt40 { get; set; }

    public int? Selejt50 { get; set; }

    public int? Selejt60 { get; set; }

    public int? Selejt70 { get; set; }

    public int? Selejt80 { get; set; }

    public int? Selejt90 { get; set; }

    public int? Selejt100 { get; set; }

    public int? Selejt110 { get; set; }

    public int? Selejt120 { get; set; }

    public int? Selejt130 { get; set; }

    public int? Selejt140 { get; set; }

    public int? Selejt150 { get; set; }

    public int? Selejt160 { get; set; }

    public int? Selejt170 { get; set; }

    public int? Selejt180 { get; set; }

    public int? Selejt190 { get; set; }

    public int? Selejt200 { get; set; }

    public int? Selejt210 { get; set; }

    public int? Selejt220 { get; set; }

    public int? Selejt230 { get; set; }

    public int? Selejt240 { get; set; }

    public int Id { get; set; }

    public virtual ICollection<IfsHeaderTable> IfsHeaderTable { get; set; } = new List<IfsHeaderTable>();
}