// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class SystemParamTable
{
    public string LineId { get; set; }

    public double Cycletime { get; set; }

    public double Minpercent { get; set; }

    public double Meanpercent { get; set; }

    public TimeSpan M1start { get; set; }

    public TimeSpan M1end { get; set; }

    public TimeSpan M1s01 { get; set; }

    public TimeSpan M1e01 { get; set; }

    public TimeSpan M1s02 { get; set; }

    public TimeSpan M1e02 { get; set; }

    public TimeSpan M1s03 { get; set; }

    public TimeSpan M1e03 { get; set; }

    public TimeSpan M1s04 { get; set; }

    public TimeSpan M1e04 { get; set; }

    public TimeSpan M1s05 { get; set; }

    public TimeSpan M1e05 { get; set; }

    public TimeSpan M1s06 { get; set; }

    public TimeSpan M1e06 { get; set; }

    public TimeSpan M1s07 { get; set; }

    public TimeSpan M1e07 { get; set; }

    public TimeSpan M1s08 { get; set; }

    public TimeSpan M1e08 { get; set; }

    public TimeSpan M1s09 { get; set; }

    public TimeSpan M1e09 { get; set; }

    public TimeSpan M2start { get; set; }

    public TimeSpan M2end { get; set; }

    public TimeSpan M2s01 { get; set; }

    public TimeSpan M2e01 { get; set; }

    public TimeSpan M2s02 { get; set; }

    public TimeSpan M2e02 { get; set; }

    public TimeSpan M2s03 { get; set; }

    public TimeSpan M2e03 { get; set; }

    public TimeSpan M2s04 { get; set; }

    public TimeSpan M2e04 { get; set; }

    public TimeSpan M2s05 { get; set; }

    public TimeSpan M2e05 { get; set; }

    public TimeSpan M2s06 { get; set; }

    public TimeSpan M2e06 { get; set; }

    public TimeSpan M2s07 { get; set; }

    public TimeSpan M2e07 { get; set; }

    public TimeSpan M2s08 { get; set; }

    public TimeSpan M2e08 { get; set; }

    public TimeSpan M2s09 { get; set; }

    public TimeSpan M2e09 { get; set; }

    public TimeSpan M3start { get; set; }

    public TimeSpan M3end { get; set; }

    public TimeSpan M3s01 { get; set; }

    public TimeSpan M3e01 { get; set; }

    public TimeSpan M3s02 { get; set; }

    public TimeSpan M3e02 { get; set; }

    public TimeSpan M3s03 { get; set; }

    public TimeSpan M3e03 { get; set; }

    public TimeSpan M3s04 { get; set; }

    public TimeSpan M3e04 { get; set; }

    public TimeSpan M3s05 { get; set; }

    public TimeSpan M3e05 { get; set; }

    public TimeSpan M3s06 { get; set; }

    public TimeSpan M3e06 { get; set; }

    public TimeSpan M3s07 { get; set; }

    public TimeSpan M3e07 { get; set; }

    public TimeSpan M3s08 { get; set; }

    public TimeSpan M3e08 { get; set; }

    public TimeSpan M3s09 { get; set; }

    public TimeSpan M3e09 { get; set; }

    public double? Wasterate { get; set; }

    public string Linename { get; set; }

    public string Linelogo { get; set; }

    public string Linelogo1 { get; set; }

    public int Id { get; set; }

    public int? OeestationId { get; set; }

    public int? LocationId { get; set; }

    public virtual ICollection<EasyMesjob> EasyMesjob { get; set; } = new List<EasyMesjob>();

    public virtual ICollection<EasyMesstatus> EasyMesstatus { get; set; } = new List<EasyMesstatus>();

    public virtual ICollection<EasyMesttstypes> EasyMesttstypes { get; set; } = new List<EasyMesttstypes>();

    public virtual Location Location { get; set; }

    public virtual ICollection<ReportUsers> ReportUsers { get; set; } = new List<ReportUsers>();
}