// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class TableTypes
{
    public string LineId { get; set; }

    public int TypeId { get; set; }

    public string TypeName { get; set; }

    public string ShortName { get; set; }

    public bool? St15Fk1enable { get; set; }

    public int? St15Fk1prNr { get; set; }

    public string St15Fk1prName { get; set; }

    public bool? St15Vtenable { get; set; }

    public bool? St17Fk2enable { get; set; }

    public int? St17Fk2prNr { get; set; }

    public string St17Fk2prName { get; set; }

    public bool? St18Dgenable { get; set; }

    public float? St18Dgvmin { get; set; }

    public float? St18Dgvmax { get; set; }

    public float? St18Dgimin { get; set; }

    public float? St18Dgimax { get; set; }

    public bool? St18Ksenable { get; set; }

    public float? St18Ksumin { get; set; }

    public float? St18Ksumax { get; set; }

    public float? St18Ksimin { get; set; }

    public float? St18Ksimax { get; set; }

    public bool? St18Drenable { get; set; }

    public bool? St18Drplus { get; set; }

    public bool? St18Drminus { get; set; }

    public bool? St18Bguenable { get; set; }

    public bool? St19Bgoenable { get; set; }

    public bool? St19Mkenable { get; set; }

    public bool? St19Kenable { get; set; }

    public float? St19Kc { get; set; }

    public int? St19Ktolminus { get; set; }

    public int? St19Ktolplus { get; set; }

    public int? St19Ku { get; set; }

    public int? St19Kfr { get; set; }

    public bool? St19KautoRange { get; set; }

    public string St19Speed { get; set; }

    public int? St19Range { get; set; }

    public int? St20LaserPrNr { get; set; }

    public double? CycleTime { get; set; }

    public int? Length { get; set; }
}