// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class TablePlannedDownTime
{
    public string LineId { get; set; }

    public int Muszak { get; set; }

    public TimeSpan Start { get; set; }

    public TimeSpan End { get; set; }

    public string Status { get; set; }

    public int Id { get; set; }
}