// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class ViewIfsValueTable
{
    public int Id { get; set; }

    public int IfsheaderId { get; set; }

    public int FailureCodeId { get; set; }

    public int? BadParts { get; set; }

    public string LineId { get; set; }

    public DateTime StartTime { get; set; }

    public int ShiftId { get; set; }

    public int Muszak { get; set; }

    public string ShiftDescription { get; set; }

    public string ShiftDescriptionEn { get; set; }

    public string FailureId { get; set; }

    public string FailureDescription { get; set; }

    public string FailureDescriptionEn { get; set; }

    public int FailureClassId { get; set; }

    public string ClassCodeId { get; set; }

    public string ClassCodeDescription { get; set; }

    public string ClassCodeDescriptionEn { get; set; }

    public string DetectId { get; set; }

    public string DetectDescription { get; set; }

    public string DetectDescriptionEn { get; set; }
}