// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class ViewLzHours
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Company { get; set; }

    public string Category { get; set; }

    public double? Hours { get; set; }
}