// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class ViewReportUsers
{
    public int Id { get; set; }

    public string LineId { get; set; }

    public string UserName { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Description { get; set; }

    public string DescriptionEn { get; set; }

    public bool? Active { get; set; }
}