// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIS.EISModels
{
    public partial class ViewShiftViewResult
    {
        public string LineID { get; set; }
        public DateTime? StartTime { get; set; }
        public int? Muszak { get; set; }
        public DateTime? TimeStamp { get; set; }
        public int? TS { get; set; }
        public int? Hour { get; set; }
        public int? Time { get; set; }
        public bool? NOK { get; set; }
        public int? WTNR { get; set; }
        public string Status { get; set; }
        public int? CT { get; set; }
        public int CNT { get; set; }
        public int Request { get; set; }
        public double? OEE { get; set; }
        public string Type { get; set; }
    }
}
