// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIS.EISModels
{
    public partial class ViewShiftTableResult
    {
        public int? Hourly { get; set; }
        public int? Counter { get; set; }
    }
}
