// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class ViewLzKefetartoTable
{
    public int Id { get; set; }

    public int MuveletId { get; set; }

    public int Muveletszam { get; set; }

    public string Muveletreszlet { get; set; }

    public string Description { get; set; }

    public string Search { get; set; }

    public bool Interval { get; set; }

    public int KefetartoId { get; set; }

    public string Kefetartoszam { get; set; }

    public string Tipus { get; set; }
}