// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class ViewCttableUpdate
{
    public DateTime TimeStamp { get; set; }

    public string LineId { get; set; }

    public int StationId { get; set; }

    public double? Ct { get; set; }

    public string Status { get; set; }

    public double? Pt { get; set; }

    public double? Wt { get; set; }

    public DateTime? StartTime { get; set; }

    public int? Muszak { get; set; }

    public double? LongCt { get; set; }

    public int? LongStep { get; set; }

    public int? TesterId { get; set; }

    public int? TesterSubId { get; set; }

    public double? Xct { get; set; }

    public double? Xpt { get; set; }

    public double? Xwt { get; set; }

    public bool? Nok { get; set; }

    public int? Wtnr { get; set; }

    public int? Type { get; set; }

    public bool? Cutting { get; set; }

    public bool? Dummies { get; set; }

    public bool? Leerfahren { get; set; }

    public bool? Active { get; set; }

    public bool? Modified { get; set; }

    public bool? Sent2Cloud { get; set; }

    public DateTime? EndTime { get; set; }

    public string TypeId { get; set; }

    public string OldTypeId { get; set; }

    public string AlertLevel { get; set; }

    public string LastAlertLevel { get; set; }

    public string Dtstatus { get; set; }

    public int Id { get; set; }

    public int? Dt { get; set; }

    public int? Downtime { get; set; }
}