// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class ViewGbmDownTimeReasons
{
    public DateTime TimeStamp { get; set; }

    public string LineId { get; set; }

    public int? StationId { get; set; }

    public double? Ct { get; set; }

    public string Status { get; set; }

    public double? Pt { get; set; }

    public double? Wt { get; set; }

    public DateTime? StartTime { get; set; }

    public int? Muszak { get; set; }

    public int? Wtnr { get; set; }

    public int? Type { get; set; }
}