// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class ViewLzMunkanapTable
{
    public int Id { get; set; }

    public DateTime? Datum { get; set; }

    public int MunkaId { get; set; }

    public string Hetnapja { get; set; }

    public string Short { get; set; }

    public string Description { get; set; }

    public bool Munkanap { get; set; }

    public bool Unnep { get; set; }

    public bool Pihenonap { get; set; }
}