// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class ViewIfsValueSearchTable
{
    public int Id { get; set; }

    public string LineId { get; set; }

    public DateTime StartTime { get; set; }

    public int ShiftId { get; set; }

    public string FailureId { get; set; }

    public string Description { get; set; }

    public string DescriptionEn { get; set; }

    public int? BadParts { get; set; }

    public string ClassCodeId { get; set; }

    public string Fccdescription { get; set; }

    public string FccdescriptionEn { get; set; }

    public string DetectId { get; set; }

    public string DetDescription { get; set; }

    public string DetDescriptionEn { get; set; }
}