// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class ViewLzAbFor
{
    public int DolgozoId { get; set; }

    public string DolgozoNeve { get; set; }

    public int Muveletszam { get; set; }

    public string Muveletreszlet { get; set; }

    public string Du { get; set; }

    public string Kefetartoszam { get; set; }

    public int? Darab { get; set; }

    public double Ora { get; set; }

    public DateTime Datum { get; set; }

    public string Megjegyzes { get; set; }
}