// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class ViewIfsFailureCodeTable
{
    public int Id { get; set; }

    public string LineId { get; set; }

    public string FailureId { get; set; }

    public string Description { get; set; }

    public string DescriptionEn { get; set; }

    public int FailureClassId { get; set; }

    public string ClassCodeId { get; set; }

    public string ClassCodeDetection { get; set; }

    public string ClassCodeDetectionEn { get; set; }

    public int DetectionId { get; set; }

    public string DetectId { get; set; }

    public string DetectDescription { get; set; }

    public string DetectDescriptionEn { get; set; }
}