// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class ViewLzCompetency
{
    public int DolgozoId { get; set; }

    public string DolgozoNeve { get; set; }

    public int? OsszesDarab { get; set; }

    public double? OsszesOra { get; set; }

    public int? Darab { get; set; }

    public DateTime? Last { get; set; }

    public string Ct { get; set; }

    public int Muveletszam { get; set; }

    public string Muveletreszlet { get; set; }

    public string Description { get; set; }

    public string Kefetartoszam { get; set; }

    public string Tipus { get; set; }

    public int MuveletId { get; set; }

    public int KefetartoId { get; set; }

    public int? CsoportId { get; set; }

    public bool Interval { get; set; }
}