// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIS.EISModels;

public partial class ViewKpivalues
{
    public int Id { get; set; }

    public int? YearPrev { get; set; }

    public int Year { get; set; }

    public int KpiheaderId { get; set; }

    public string DescriptionHu { get; set; }

    public string DescriptionEn { get; set; }

    public string DescriptionDe { get; set; }

    public int ProcessId { get; set; }

    public string ProcessName { get; set; }

    public string ResponsibleName { get; set; }

    public string SummantionName { get; set; }

    public string DataSourceName { get; set; }

    public string UnitNameEn { get; set; }

    public string UnitNameHu { get; set; }

    public string UnitNameDe { get; set; }

    public string ExpectationName { get; set; }

    public double? TargetPrev { get; set; }

    public double? Target01 { get; set; }

    public double? Target02 { get; set; }

    public double? Target03 { get; set; }

    public double? Target04 { get; set; }

    public double? Target05 { get; set; }

    public double? Target06 { get; set; }

    public double? Target07 { get; set; }

    public double? Target08 { get; set; }

    public double? Target09 { get; set; }

    public double? Target10 { get; set; }

    public double? Target11 { get; set; }

    public double? Target12 { get; set; }

    public double? TargetNext { get; set; }

    public double? ValuePrev { get; set; }

    public double? Value01 { get; set; }

    public double? Value02 { get; set; }

    public double? Value03 { get; set; }

    public double? Value04 { get; set; }

    public double? Value05 { get; set; }

    public double? Value06 { get; set; }

    public double? Value07 { get; set; }

    public double? Value08 { get; set; }

    public double? Value09 { get; set; }

    public double? Value10 { get; set; }

    public double? Value11 { get; set; }

    public double? Value12 { get; set; }

    public double? ValueNext { get; set; }

    public int StatusPrev { get; set; }

    public int Status01 { get; set; }

    public int Status02 { get; set; }

    public int Status03 { get; set; }

    public int Status04 { get; set; }

    public int Status05 { get; set; }

    public int Status06 { get; set; }

    public int Status07 { get; set; }

    public int Status08 { get; set; }

    public int Status09 { get; set; }

    public int Status10 { get; set; }

    public int Status11 { get; set; }

    public int Status12 { get; set; }

    public int StatusNext { get; set; }

    public int? SortedId { get; set; }

    public bool? Visible { get; set; }

    public string Format { get; set; }
}