//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EIS.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [None].
        /// </summary>
        public static string _None_ {
            get {
                return ResourceManager.GetString("[None]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string All_rights_reserved_ {
            get {
                return ResourceManager.GetString("All rights reserved.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string Are_you_sure_you_want_to_delete_this_ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete this?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string Back_to_list {
            get {
                return ResourceManager.GetString("Back to list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Boards {
            get {
                return ResourceManager.GetString("Boards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project title.
        /// </summary>
        public static string BoardTitle {
            get {
                return ResourceManager.GetString("BoardTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project title.
        /// </summary>
        public static string BoardGroupId
        {
            get
            {
                return ResourceManager.GetString("BoardGroupId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project title.
        /// </summary>
        public static string BoardGroup
        {
            get
            {
                return ResourceManager.GetString("BoardGroup", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task ID.
        /// </summary>
        public static string CardId {
            get {
                return ResourceManager.GetString("CardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsibles.
        /// </summary>
        public static string CardsOfUsers {
            get {
                return ResourceManager.GetString("CardsOfUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clarified 50%.
        /// </summary>
        public static string Clarified_50_ {
            get {
                return ResourceManager.GetString("Clarified 50%", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Close
        {
            get
            {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Competencies
        {
            get
            {
                return ResourceManager.GetString("Competencies", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Competency
        {
            get
            {
                return ResourceManager.GetString("Competency", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string CompetencyMatrix
        {
            get
            {
                return ResourceManager.GetString("CompetencyMatrix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string CompetencyMatrixes
        {
            get
            {
                return ResourceManager.GetString("CompetencyMatrixes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Confirmpassword {
            get {
                return ResourceManager.GetString("Confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard....
        /// </summary>
        public static string Copy_to_clipboard___ {
            get {
                return ResourceManager.GetString("Copy to clipboard...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string Create_a_new_account_ {
            get {
                return ResourceManager.GetString("Create a new account.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string Create_new {
            get {
                return ResourceManager.GetString("Create new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string Created_by {
            get {
                return ResourceManager.GetString("Created by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create date.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycletime.
        /// </summary>
        public static string Cycletime {
            get {
                return ResourceManager.GetString("Cycletime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted 0%.
        /// </summary>
        public static string Deleted_0_ {
            get {
                return ResourceManager.GetString("Deleted 0%", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done 100%.
        /// </summary>
        public static string Done_100_ {
            get {
                return ResourceManager.GetString("Done 100%", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downtime.
        /// </summary>
        public static string Downtime {
            get {
                return ResourceManager.GetString("Downtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original due date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiencies.
        /// </summary>
        public static string Efficiencies {
            get {
                return ResourceManager.GetString("Efficiencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency.
        /// </summary>
        public static string Efficiency {
            get {
                return ResourceManager.GetString("Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email invalid.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to PDF file....
        /// </summary>
        public static string Export_to_PDF_file___ {
            get {
                return ResourceManager.GetString("Export to PDF file...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish date.
        /// </summary>
        public static string FinishDate {
            get {
                return ResourceManager.GetString("FinishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name required.
        /// </summary>
        public static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi,.
        /// </summary>
        public static string Hi_ {
            get {
                return ResourceManager.GetString("Hi,", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, Visitor.
        /// </summary>
        public static string Hi__Visitor {
            get {
                return ResourceManager.GetString("Hi, Visitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am already a member.
        /// </summary>
        public static string I_already_have_a_membership {
            get {
                return ResourceManager.GetString("I already have a membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID required.
        /// </summary>
        public static string IdRequired {
            get {
                return ResourceManager.GetString("IdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress 75%.
        /// </summary>
        public static string In_Progress_75_ {
            get {
                return ResourceManager.GetString("In Progress 75%", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPI.
        /// </summary>
        public static string Kpiid {
            get {
                return ResourceManager.GetString("Kpiid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KPIs.
        /// </summary>
        public static string KPI
        {
            get
            {
                return ResourceManager.GetString("KPI", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KPIs.
        /// </summary>
        public static string KPIs {
            get {
                return ResourceManager.GetString("KPIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Language_ {
            get {
                return ResourceManager.GetString("Language:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Log_In {
            get {
                return ResourceManager.GetString("Log In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open 25%.
        /// </summary>
        public static string Open_25_ {
            get {
                return ResourceManager.GetString("Open 25%", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent ID.
        /// </summary>
        public static string ParentId {
            get {
                return ResourceManager.GetString("ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print....
        /// </summary>
        public static string Print___ {
            get {
                return ResourceManager.GetString("Print...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorities.
        /// </summary>
        public static string Priorities {
            get {
                return ResourceManager.GetString("Priorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorities title.
        /// </summary>
        public static string PrioritiesTitle {
            get {
                return ResourceManager.GetString("PrioritiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority ID.
        /// </summary>
        public static string PriorityID {
            get {
                return ResourceManager.GetString("PriorityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority title.
        /// </summary>
        public static string PriorityTitle {
            get {
                return ResourceManager.GetString("PriorityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Remember_Me {
            get {
                return ResourceManager.GetString("Remember Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language selection requested:.
        /// </summary>
        public static string Request_culture_provider_ {
            get {
                return ResourceManager.GetString("Request culture provider:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        public static string RescheduleDate {
            get {
                return ResourceManager.GetString("RescheduleDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RoleId
        {
            get
            {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RoleName
        {
            get
            {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to CSV file....
        /// </summary>
        public static string Save_to_CSV_file___ {
            get {
                return ResourceManager.GetString("Save to CSV file...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to Excel file....
        /// </summary>
        public static string Save_to_Excel_file___ {
            get {
                return ResourceManager.GetString("Save to Excel file...", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Selected
        {
            get
            {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string Search_ {
            get {
                return ResourceManager.GetString("Search:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search text....
        /// </summary>
        public static string Search_text___ {
            get {
                return ResourceManager.GetString("Search text...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting time.
        /// </summary>
        public static string Setting_time {
            get {
                return ResourceManager.GetString("Setting time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Columns.
        /// </summary>
        public static string Show_Hide_Columns {
            get {
                return ResourceManager.GetString("Show/Hide Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Sign_In {
            get {
                return ResourceManager.GetString("Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to start your session.
        /// </summary>
        public static string Sign_in_to_start_your_session {
            get {
                return ResourceManager.GetString("Sign in to start your session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up using Facebook.
        /// </summary>
        public static string Sign_up_using_Facebook {
            get {
                return ResourceManager.GetString("Sign up using Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up using Google+.
        /// </summary>
        public static string Sign_up_using_Google_ {
            get {
                return ResourceManager.GetString("Sign up using Google+", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project title.
        /// </summary>
        public static string SortedId
        {
            get
            {
                return ResourceManager.GetString("SortedId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status ID.
        /// </summary>
        public static string StatusID {
            get {
                return ResourceManager.GetString("StatusID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status title.
        /// </summary>
        public static string StatusTitle {
            get {
                return ResourceManager.GetString("StatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        public static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 6 characters long which contains a uppercase letter, a number and a special character..
        /// </summary>
        public static string Thepasswordlength {
            get {
                return ResourceManager.GetString("Thepasswordlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string Thepasswordmatch {
            get {
                return ResourceManager.GetString("Thepasswordmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeStamp.
        /// </summary>
        public static string TimeStamp {
            get {
                return ResourceManager.GetString("TimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string TIP {
            get {
                return ResourceManager.GetString("TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string TIPs {
            get {
                return ResourceManager.GetString("TIPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleEn
        {
            get
            {
                return ResourceManager.GetString("TitleEn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title required.
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools of Admins.
        /// </summary>
        public static string Tools_of_Admins {
            get {
                return ResourceManager.GetString("Tools of Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID1.
        /// </summary>
        public static string UserId1 {
            get {
                return ResourceManager.GetString("UserId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID2.
        /// </summary>
        public static string UserId2 {
            get {
                return ResourceManager.GetString("UserId2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID3.
        /// </summary>
        public static string UserId3 {
            get {
                return ResourceManager.GetString("UserId3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Users.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name required.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
